### ISSUE TITLE
attributes on <head> not supported

### ISSUE THREAD

**Issue by iplanwebsites** [ayal/headly#1]
Great lib!

In order to a custom object (not just "og:type"=websites), a prefix attribute is required on the head, but Meteor doesn't appreciate having on by default, and headly fails to inject it like the other meta tags.

Any clues on how it'd be possible to have Facebook gets the prefix attribute of the head element as specified in the open-graph examples?

**Comment by iplanwebsites** [comment]
for instance, here's the required HEAD for music.albums type:

``` html
 <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# music: http://ogp.me/ns/music#">
 <meta property="og:type"        content="music.album" />

```

**Comment by iplanwebsites** [comment]
Looks like the attribute is not mandatory, but it'd be curious to know how it'd be possible to access it.

**Comment by ayal** [comment]
@iplanwebsites I think this prefix is not needed
It's not mentioned anywhere in the official documentation:

https://developers.facebook.com/docs/opengraphprotocol/

but to directly answer your question, with headly out-of-the-box it's not possible. But you can do the code change yourself if you find where mrt put headly's code.. you can just change this chunk:

``` javascript
  if (head) {
            res.write('<head>');
            res.write(head);
            res.write('</head>');
            }
```

to this:

``` javascript
  if (head) {
            res.write(head);    
}
```

and then use it like so: 

``` javascript
Meteor.headly.config({tagsForRequest: function(req) {
  ... do something dynamic here, i.e get title from db based on url param ...
  return '<head prefix='XXXYYY'><meta property="og:title" content="<DYNAMIC TITLE>" /></head>';
}});
```

just make sure you open/close/render the head tag correctly

**Comment by iplanwebsites** [comment]
Thanks @ayal ! That's very helpful!
