### ISSUE TITLE
Spiderable compatibility

### ISSUE THREAD

**Issue by iplanwebsites** [ayal/headly#3]
The spiderable meteor package makes the site indexable by search engines using phantom-js.

Once activated, FacebookExternal hits gets served with the spiderable-generated stuff, not the Headly Meta. What would be the most elegant way to have both packages play nicely?

PS: I also had troubles with MRT, so I use Headly_server.js directly, if that makes any difference.

**Comment by ayal** [comment]
I think that if you use spiderable you don't need headly. See my comment
here on how to use spiderable to serve Facebook with the correct meta-tags:
https://github.com/meteor/meteor/pull/411

If you still choose to have them both, test it and see which one gets the
"preference" for serving the facebookexternalhit agent, maybe it depends on
the order they appear in the .meteor/packages file...

---

**Comment by iplanwebsites** [comment]
Thanks for the timely answer!
On thing I really liked about Headly was the possibility to generate these metas-tags only on facebook-external-hits.
Do you know what user-agent pahntom-js define on client-side for facebook request?
Or is there a isPhantom or isSpiderable hook that'd be more appropriate?

**Comment by ayal** [comment]
Hi sorry for the very late reply, i somehow missed this question and have not tended to headly in a long time.
I also don't know the answers to the questions you asked here.. I can assume phantomjs lets you set the user-agent himself when you use it, so you should ask the Meteor guys about that.
